name: Run experiment 2

inputs:
    repositoryUrl:
        required: true
        type: string
    branch:
        required: true
        type: string
    task:
        required: true
        type: string

runs:
    using: "composite"
    steps:
        - name: Run Gradle Experiment 2
          run: |
              cd gradle-enterprise-gradle-build-validation
              ./02-validate-local-build-caching-same-location.sh -r ${{ inputs.repositoryUrl }} -b ${{ inputs.branch }} -t ${{ inputs.task }} -s https://ge.solutions-team.gradle.com
          shell: bash
