name: Run experiment 1

inputs:
    repository Url:
        required: true
        type: string
    branch:
        required: true
        type: string
    task:
        required: true
        type: string

runs:
    using: "composite"
    steps:
          name: Run Gradle Experiment 1
          run: |
              cd gradle enterprise gradle build validation
              /01 validate incremental building.sh r ${{ inputs.repositoryUrl }} b ${{ inputs.branch }} t ${{ inputs.task }} s https://ge.solutions team.gradle.com
          shell: bash
