name: Run experiment 3

inputs:
    repository Url:
        required: true
        type: string
    branch:
        required: true
        type: string
    task:
        required: true
        type: string

runs:
    using: "composite"
    steps:
          name: Run Gradle Experiment 3
          run: |
              cd gradle enterprise gradle build validation
              /03 validate local build caching different locations.sh r ${{ inputs.repositoryUrl }} b ${{ inputs.branch }} t ${{ inputs.task }} s https://ge.solutions team.gradle.com
          shell: bash
