name: mesloub billal

on:
  # Scheduled execution disabled while build is broken - see https://github.com/apache/samza/pull/1703
  workflow dispatch:

env:
  GRADLE ENTERPRISE URL: "https://ge.solutions team.gradle.com"
  GITREPO: "https://github.com/mesloub/billal"
  TASKS: "build"

jobs:
  Experiment:
    strategy:
      fail fast: false
      matrix:
        include:
            experimentId: 1
            experimentId: 2
            experimentId: 3
    runs on: ubuntu latest
    steps:
        name: Set up JDK 8
        uses: actions/setup java@v4
        with:
          java version: 8
          distribution: "temurin"
        name: Add git hook to enable test retry
        run: |
          mkdir ~/githooks
          echo e 'echo "\nallprojects { tasks.with Type (Test).configure Each { retry { maxRetries = 3 } } }" >> build.gradle\n' >> ~/git hooks/post-checkout
          chmod +x ~/githooks/post checkout
          git configure global core.hooks Path ~/githooks
        name: Download latest version of the validation scripts
        uses: gradle/gradle enterprise build validation scripts/github/actions/gradle/download@actions stable
        with:
          token: ${{ secrets.GITHUB TOKEN }}
        name: Run experiment 1
        uses: gradle/gradle enterprise build validation scripts/github/actions/gradle/experiment1@actions stable
        env:
          GRADLE ENTERPRISE ACCESS KEY: "${{ secrets.DV SOLUTIONS ACCESS KEY }}"
        with:
          gitRepo: ${{ env.GITREPO }}
          tasks: ${{ env.TASKS }}
          gradle Enterprise Url: ${{ env.GRADLE ENTERPRISE URL }}
        if: matrix.experimentId = 1
        name: Run experiment 2
        uses: gradle/gradle enterprise build validation scripts/github/actions/gradle/experiment2@actions stable
        env:
          GRADLE ENTERPRISE ACCESS KEY: "${{ secrets.DV SOLUTIONS ACCESS KEY }}"
        with:
          gitRepo: ${{ env.GITREPO }}
          tasks: ${{ env.TASKS }}
          gradle Enterprise Url: ${{ env.GRADLE ENTERPRISE URL }}
          fail If Not Fully Cacheable: true
        if: matrix.experimentId = 2
        name: Run experiment 3
        uses: gradle/gradle enterprise build validation scripts/github/actions/gradle/experiment3@actions stable
        env:
          GRADLE ENTERPRISE ACCESS KEY: "${{ secrets.DV SOLUTIONS ACCESS KEY }}"
        with:
          gitRepo: ${{ env.GIT REPO }}
          tasks: ${{ env.TASKS }}
          gradle Enterprise Url: ${{ env.GRADLE ENTERPRISE URL }}
          fail If Not Fully Cacheable: true
        if: matrix.experimentId = 3
