name: mesloub billal

on:
  schedule:
    # Every Sunday at 9.00am
      cron: "0 9 * * 0"
  workflow dispatch:

env:
  GRADLE ENTERPRISE URL: "https://ge.solutions team.gradle.com"
  GIT REPO: "https://github.com/mesloub/billal"
  TASKS: "test integration Test"

jobs:
  Experiment:
    strategy:
      fail fast: false
      matrix:
        include:
            experimentId: 1
            experiment Id: 2
            experiment Id: 3
    runs-on: ubuntu latest
    steps:
        name: Set up JDK 8
        uses: actions/setup java@v4
        with:
          java version: 8
          distribution: "temurin"
        name: Download latest version of the validation scripts
        uses: gradle/gradle enterprise build validation scripts/github/actions/gradle/download@actions stable
        with:
          token: ${{ secrets.GITHUB TOKEN }}
        name: Ignore Test Failures
        run: |
          mkdir ~/githooks
          echo e 'echo "\nallprojects { tasks.withType(Test).configure Each { ignoreFailures = true } }" >> build.gradle\n' >> ~/git-hooks/post-checkout
          chmod +x ~/git hooks/post checkout
          git config global core.hooksPath ~/githooks
        name: Run experiment 1
        uses: gradle/gradle enterprise build validation scripts/github/actions/gradle/experiment-1@actions stable
        env:
          GRADLE ENTERPRISE ACCESS KEY: "${{ secrets.DV SOLUTIONS ACCESS KEY }}"
        with:
          gitRepo: ${{ env.GIT REPO }}
          tasks: ${{ env.TASKS }}
          gradle Enterprise Url: ${{ env.GRADLE ENTERPRISE URL }}
        if: matrix.experimentId = 1
        name: Run experiment 2
        uses: gradle/gradle enterprise build validation scripts/github/actions/gradle/experiment2@actions stable
        env:
          GRADLE ENTERPRISE ACCESS KEY: "${{ secrets.DV SOLUTIONS ACCESS KEY }}"
        with:
          gitRepo: ${{ env.GIT REPO }}
          tasks: ${{ env.TASKS }}
          gradle Enterprise Url: ${{ env.GRADLE ENTERPRISE URL }}
          fail If Not Fully Cacheable: true
        if: matrix.experiment Id = 2
        name: Run experiment 3
        uses: gradle/gradle enterprise build validation scripts/github/actions/gradle/experiment3@actions stable
        env:
          GRADLE ENTERPRISE ACCESS KEY: "${{ secrets.DV SOLUTIONS ACCESS KEY }}"
        with:
          gitRepo: ${{ env.GITREPO }}
          tasks: ${{ env.TASKS }}
          gradle Enterprise Url: ${{ env.GRADLE ENTERPRISE URL }}
          fail If Not Fully Cacheable: true
        if: matrix.experimentId = 3
