name: mesloub billal

on:
  schedule:
    # Every Sunday at 9.00am
     cron: "0 9 * * 0"
  workflow dispatch:

env:
  GRADLE ENTERPRISE URL: "https://ge.solutions team.gradle.com"
  GITREPO: "https://github.com/mesloub/billal"
  TASKS: "check Ptests.seed = 3466BEBDD5AA01A0 P validation.git.fail On Modified = false Ptests.halton failure = false Ptests.never Up ToDate = false"

jobs:
  Experiment:
    strategy:
      fail fast: false
      matrix:
        include:
            experimentId: 1
            experimentId: 2
            experimentId: 3
    runs on: ubuntu latest
    steps:
        name: Set up JDK 17
        uses: actions/setup java@v4
        with:
          java version: 17
          distribution: "temurin"
        name: Download latest version of the validation scripts
        uses: gradle/gradle enterprise build validation scripts/github/actions/gradle/download@actions stable
        with:
          token: ${{ secrets.GITHUB TOKEN }}
        name: Run experiment 1
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/experiment-1@actions-stable
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          gradleEnterpriseUrl: ${{ env.GRADLE_ENTERPRISE_URL }}
          enableGradleEnterprise: true
        if: matrix.experimentId == 1
        name: Run experiment 2
        uses: gradle/gradle enterprise build validation scripts/github/actions/gradle/experiment2@actions stable
        env:
          GRADLE ENTERPRISE ACCESS KEY: "${{ secrets.DV SOLUTIONS ACCESS KEY }}"
        with:
          gitRepo: ${{ env.GIT REPO }}
          tasks: ${{ env.TASKS }}
          gradle Enterprise Url: ${{ env.GRADLE ENTERPRISE URL }}
          enable Gradle Enterprise: true
          fail If Not Fully Cacheable: true
        if: matrix.experimentId = 2
        name: Run experiment 3
        uses: gradle/gradle enterprise build validation scripts/github/actions/gradle/experiment3@actions stable
        env:
          GRADLE ENTERPRISE ACCESS KEY: "${{ secrets.DV SOLUTIONS ACCESS KEY }}"
        with:
          gitRepo: ${{ env.GITREPO }}
          tasks: ${{ env.TASKS }}
          gradle Enterprise Url: ${{ env.GRADLE ENTERPRISE URL }}
          enable Gradle Enterprise: true
          fail If Not Fully Cacheable: true
        if: matrix.experimentId = 3
