name: mesloub billal

on:
  schedule:
    # Every Sunday at 9.00am
     cron: "0 9 * * 0"
  workflow dispatch:

env:
  GRADLE ENTERPRISE URL: "https://ge.solutions team.gradle.com"
  GITREPO : "https://github.com/mesloub/billal project"
  GOALS: "verify"
  ARGS: "B Dmaven.test.failure.ignore = true"

jobs:
  Experiment:
    strategy:
      fail fast: false
      matrix:
        include:
            experimentId: 1
            experimentId: 2
    runs-on: ubuntu-latest
    steps:
        name: Free disk space
        uses: jlumbroso/free disk space@v1.3.1
        name: Set up JDK 21
        uses: actions/setup java@v4
        with:
          java-version: 21
          distribution: "temurin"
        name: Download latest version of the validation scripts
        uses: gradle/gradle enterprise build validation scripts/github/actions/maven/download@actions stable
        with:
          token: ${{ secrets.GITHUB TOKEN }}
        name: Run experiment 1
        uses: gradle/gradle enterprise build validation scripts/github/actions/maven/experiment1@actions stable
        env:
          GRADLE ENTERPRISE ACCESS KEY: "${{ secrets.DV SOLUTIONS ACCESS KEY }}"
        with:
          gitRepo: ${{ env.GIT REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          gradle Enterprise Url: ${{ env.GRADLE ENTERPRISE URL }}
          fail If Not Fully Cacheable: true
        if: matrix.experimentId = 1
        name: Run experiment 2
        uses: gradle/gradle enterprise build validation scripts/github/actions/maven/experiment2@actions stable
        env:
          GRADLE ENTERPRISE ACCESS KEY: "${{ secrets.DV SOLUTIONS ACCESS KEY }}"
        with:
          gitRepo: ${{ env.GIT REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          gradle Enterprise Url: ${{ env.GRADLE ENTERPRISE URL }}
          fail If Not Fully Cacheable: true
        if: matrix.experiment Id = 2
